name: Build Lambda Go

on:
  workflow_call:
    inputs:
      aws-access-key-id: 
        description: 'Id de la credencial de acceso de AWS'
        required: true
        type: string

      aws-secret-access-key: 
        description: 'Key de acceso a los secretos de AWS'
        required: true
        type: string

      aws-region: 
        description: 'Región'
        required: true
        type: string

      lambda-name:
        description: 'Nombre de la función'
        required: true
        type: string
    
runs:
  using: "composite"
  steps:
    - name: Checkout code 📥
      uses: actions/checkout@v4

    - name: Set up Go 🛠
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Install dependencies 📦
      run: go mod tidy
      shell: bash

    - name: Build the Go binary 🔨
      run: GOOS=linux GOARCH=amd64 go build -tags lambda.norpc -o bootstrap main.go
      shell: bash

    - name: Zip the binary 🗜️
      run: zip main.zip bootstrap
      shell: bash

    - name: Configure AWS credentials 🔐
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Deploy to AWS Lambda 🚀
      run: |
        aws lambda update-function-code --function-name ${{ inputs.lambda-name }} --zip-file fileb://main.zip
      shell: bash
